const mongoose = require('mongoose');
const Pincode = require('./models/pincode');
require('dotenv').config();

// Comprehensive Indian PIN code data for major cities and states
const comprehensiveData = [
  // Delhi
  { pincode: '110001', officeName: 'Delhi GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Delhi Central', regionName: 'Delhi', circleName: 'Delhi', taluk: 'Delhi', district: 'Central Delhi', state: 'DELHI', country: 'INDIA', latitude: 28.6139, longitude: 77.2090 },
  { pincode: '110002', officeName: 'Delhi Sadar Bazar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Delhi Central', regionName: 'Delhi', circleName: 'Delhi', taluk: 'Delhi', district: 'North Delhi', state: 'DELHI', country: 'INDIA', latitude: 28.6587, longitude: 77.2183 },
  { pincode: '110003', officeName: 'Delhi Parliament House', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Delhi Central', regionName: 'Delhi', circleName: 'Delhi', taluk: 'Delhi', district: 'New Delhi', state: 'DELHI', country: 'INDIA', latitude: 28.6139, longitude: 77.2090 },
  { pincode: '110004', officeName: 'Delhi Bazar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Delhi Central', regionName: 'Delhi', circleName: 'Delhi', taluk: 'Delhi', district: 'Central Delhi', state: 'DELHI', country: 'INDIA', latitude: 28.6139, longitude: 77.2090 },
  { pincode: '110005', officeName: 'Delhi University', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Delhi North', regionName: 'Delhi', circleName: 'Delhi', taluk: 'Delhi', district: 'North Delhi', state: 'DELHI', country: 'INDIA', latitude: 28.6863, longitude: 77.2217 },

  // Mumbai
  { pincode: '400001', officeName: 'Mumbai GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Mumbai City East', regionName: 'Mumbai', circleName: 'Maharashtra', taluk: 'Mumbai', district: 'Mumbai', state: 'MAHARASHTRA', country: 'INDIA', latitude: 18.9750, longitude: 72.8258 },
  { pincode: '400002', officeName: 'Mandvi', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Mumbai City East', regionName: 'Mumbai', circleName: 'Maharashtra', taluk: 'Mumbai', district: 'Mumbai', state: 'MAHARASHTRA', country: 'INDIA', latitude: 18.9633, longitude: 72.8311 },
  { pincode: '400003', officeName: 'Mumbai Central H.O', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Mumbai City East', regionName: 'Mumbai', circleName: 'Maharashtra', taluk: 'Mumbai', district: 'Mumbai', state: 'MAHARASHTRA', country: 'INDIA', latitude: 18.9690, longitude: 72.8194 },
  { pincode: '400004', officeName: 'Girgaon', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Mumbai City East', regionName: 'Mumbai', circleName: 'Maharashtra', taluk: 'Mumbai', district: 'Mumbai', state: 'MAHARASHTRA', country: 'INDIA', latitude: 18.9547, longitude: 72.8173 },
  { pincode: '400005', officeName: 'Colaba', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Mumbai City East', regionName: 'Mumbai', circleName: 'Maharashtra', taluk: 'Mumbai', district: 'Mumbai', state: 'MAHARASHTRA', country: 'INDIA', latitude: 18.9151, longitude: 72.8258 },

  // Bangalore
  { pincode: '560001', officeName: 'Bangalore GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Bangalore East', regionName: 'Karnataka', circleName: 'Karnataka', taluk: 'Bangalore North', district: 'Bangalore', state: 'KARNATAKA', country: 'INDIA', latitude: 12.9716, longitude: 77.5946 },
  { pincode: '560002', officeName: 'Bangalore Corporation', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Bangalore East', regionName: 'Karnataka', circleName: 'Karnataka', taluk: 'Bangalore North', district: 'Bangalore', state: 'KARNATAKA', country: 'INDIA', latitude: 12.9716, longitude: 77.5946 },
  { pincode: '560003', officeName: 'Bangalore Fort', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Bangalore East', regionName: 'Karnataka', circleName: 'Karnataka', taluk: 'Bangalore North', district: 'Bangalore', state: 'KARNATAKA', country: 'INDIA', latitude: 12.9716, longitude: 77.5946 },
  { pincode: '560004', officeName: 'Bangalore Market', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Bangalore East', regionName: 'Karnataka', circleName: 'Karnataka', taluk: 'Bangalore North', district: 'Bangalore', state: 'KARNATAKA', country: 'INDIA', latitude: 12.9716, longitude: 77.5946 },
  { pincode: '560005', officeName: 'Fraser Town', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Bangalore East', regionName: 'Karnataka', circleName: 'Karnataka', taluk: 'Bangalore North', district: 'Bangalore', state: 'KARNATAKA', country: 'INDIA', latitude: 12.9716, longitude: 77.5946 },

  // Chennai
  { pincode: '600001', officeName: 'Chennai GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Chennai City Central', regionName: 'Tamilnadu', circleName: 'Tamilnadu', taluk: 'Chennai', district: 'Chennai', state: 'TAMIL NADU', country: 'INDIA', latitude: 13.0827, longitude: 80.2707 },
  { pincode: '600002', officeName: 'Chennai Park Town', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Chennai City Central', regionName: 'Tamilnadu', circleName: 'Tamilnadu', taluk: 'Chennai', district: 'Chennai', state: 'TAMIL NADU', country: 'INDIA', latitude: 13.0827, longitude: 80.2707 },
  { pincode: '600003', officeName: 'Chennai Egmore', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Chennai City Central', regionName: 'Tamilnadu', circleName: 'Tamilnadu', taluk: 'Chennai', district: 'Chennai', state: 'TAMIL NADU', country: 'INDIA', latitude: 13.0827, longitude: 80.2707 },
  { pincode: '600004', officeName: 'Chennai Royapettah', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Chennai City Central', regionName: 'Tamilnadu', circleName: 'Tamilnadu', taluk: 'Chennai', district: 'Chennai', state: 'TAMIL NADU', country: 'INDIA', latitude: 13.0827, longitude: 80.2707 },
  { pincode: '600005', officeName: 'Chennai Flower Bazaar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Chennai City Central', regionName: 'Tamilnadu', circleName: 'Tamilnadu', taluk: 'Chennai', district: 'Chennai', state: 'TAMIL NADU', country: 'INDIA', latitude: 13.0827, longitude: 80.2707 },

  // Kolkata
  { pincode: '700001', officeName: 'Kolkata GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Kolkata Central', regionName: 'West Bengal', circleName: 'West Bengal', taluk: 'Kolkata', district: 'Kolkata', state: 'WEST BENGAL', country: 'INDIA', latitude: 22.5726, longitude: 88.3639 },
  { pincode: '700002', officeName: 'Kolkata BBD Bag', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Kolkata Central', regionName: 'West Bengal', circleName: 'West Bengal', taluk: 'Kolkata', district: 'Kolkata', state: 'WEST BENGAL', country: 'INDIA', latitude: 22.5726, longitude: 88.3639 },
  { pincode: '700003', officeName: 'Kolkata Alipore', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Kolkata Central', regionName: 'West Bengal', circleName: 'West Bengal', taluk: 'Kolkata', district: 'Kolkata', state: 'WEST BENGAL', country: 'INDIA', latitude: 22.5726, longitude: 88.3639 },
  { pincode: '700004', officeName: 'Kolkata Ballygunge', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Kolkata Central', regionName: 'West Bengal', circleName: 'West Bengal', taluk: 'Kolkata', district: 'Kolkata', state: 'WEST BENGAL', country: 'INDIA', latitude: 22.5726, longitude: 88.3639 },
  { pincode: '700005', officeName: 'Kolkata Park Street', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Kolkata Central', regionName: 'West Bengal', circleName: 'West Bengal', taluk: 'Kolkata', district: 'Kolkata', state: 'WEST BENGAL', country: 'INDIA', latitude: 22.5726, longitude: 88.3639 },

  // Hyderabad
  { pincode: '500001', officeName: 'Hyderabad GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Hyderabad City', regionName: 'Andhra Pradesh', circleName: 'Andhra Pradesh', taluk: 'Hyderabad', district: 'Hyderabad', state: 'TELANGANA', country: 'INDIA', latitude: 17.3850, longitude: 78.4867 },
  { pincode: '500002', officeName: 'Hyderabad Jubilee Hills', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Hyderabad City', regionName: 'Andhra Pradesh', circleName: 'Andhra Pradesh', taluk: 'Hyderabad', district: 'Hyderabad', state: 'TELANGANA', country: 'INDIA', latitude: 17.3850, longitude: 78.4867 },
  { pincode: '500003', officeName: 'Hyderabad Banjara Hills', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Hyderabad City', regionName: 'Andhra Pradesh', circleName: 'Andhra Pradesh', taluk: 'Hyderabad', district: 'Hyderabad', state: 'TELANGANA', country: 'INDIA', latitude: 17.3850, longitude: 78.4867 },
  { pincode: '500004', officeName: 'Hyderabad Kachiguda', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Hyderabad City', regionName: 'Andhra Pradesh', circleName: 'Andhra Pradesh', taluk: 'Hyderabad', district: 'Hyderabad', state: 'TELANGANA', country: 'INDIA', latitude: 17.3850, longitude: 78.4867 },
  { pincode: '500005', officeName: 'Hyderabad Secunderabad', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Hyderabad City', regionName: 'Andhra Pradesh', circleName: 'Andhra Pradesh', taluk: 'Hyderabad', district: 'Hyderabad', state: 'TELANGANA', country: 'INDIA', latitude: 17.3850, longitude: 78.4867 },

  // Ahmedabad
  { pincode: '380001', officeName: 'Ahmedabad GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Ahmedabad City', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Ahmedabad', district: 'Ahmedabad', state: 'GUJARAT', country: 'INDIA', latitude: 23.0225, longitude: 72.5714 },
  { pincode: '380002', officeName: 'Ahmedabad Maninagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Ahmedabad City', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Ahmedabad', district: 'Ahmedabad', state: 'GUJARAT', country: 'INDIA', latitude: 23.0225, longitude: 72.5714 },
  { pincode: '380003', officeName: 'Ahmedabad Gheekanta', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Ahmedabad City', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Ahmedabad', district: 'Ahmedabad', state: 'GUJARAT', country: 'INDIA', latitude: 23.0225, longitude: 72.5714 },
  { pincode: '380004', officeName: 'Ahmedabad Ellisbridge', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Ahmedabad City', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Ahmedabad', district: 'Ahmedabad', state: 'GUJARAT', country: 'INDIA', latitude: 23.0225, longitude: 72.5714 },
  { pincode: '380005', officeName: 'Ahmedabad Paldi', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Ahmedabad City', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Ahmedabad', district: 'Ahmedabad', state: 'GUJARAT', country: 'INDIA', latitude: 23.0225, longitude: 72.5714 },

  // Jaipur
  { pincode: '302001', officeName: 'Jaipur GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Jaipur City', regionName: 'Rajasthan', circleName: 'Rajasthan', taluk: 'Jaipur', district: 'Jaipur', state: 'RAJASTHAN', country: 'INDIA', latitude: 26.9124, longitude: 75.7873 },
  { pincode: '302002', officeName: 'Jaipur Sindhi Camp', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Jaipur City', regionName: 'Rajasthan', circleName: 'Rajasthan', taluk: 'Jaipur', district: 'Jaipur', state: 'RAJASTHAN', country: 'INDIA', latitude: 26.9124, longitude: 75.7873 },
  { pincode: '302003', officeName: 'Jaipur C Scheme', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Jaipur City', regionName: 'Rajasthan', circleName: 'Rajasthan', taluk: 'Jaipur', district: 'Jaipur', state: 'RAJASTHAN', country: 'INDIA', latitude: 26.9124, longitude: 75.7873 },
  { pincode: '302004', officeName: 'Jaipur Bani Park', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Jaipur City', regionName: 'Rajasthan', circleName: 'Rajasthan', taluk: 'Jaipur', district: 'Jaipur', state: 'RAJASTHAN', country: 'INDIA', latitude: 26.9124, longitude: 75.7873 },
  { pincode: '302005', officeName: 'Jaipur Malviya Nagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Jaipur City', regionName: 'Rajasthan', circleName: 'Rajasthan', taluk: 'Jaipur', district: 'Jaipur', state: 'RAJASTHAN', country: 'INDIA', latitude: 26.9124, longitude: 75.7873 },

  // Pune
  { pincode: '411001', officeName: 'Pune City', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Pune City East', regionName: 'Maharashtra', circleName: 'Maharashtra', taluk: 'Pune', district: 'Pune', state: 'MAHARASHTRA', country: 'INDIA', latitude: 18.5204, longitude: 73.8567 },
  { pincode: '411002', officeName: 'Pune Camp', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Pune City East', regionName: 'Maharashtra', circleName: 'Maharashtra', taluk: 'Pune', district: 'Pune', state: 'MAHARASHTRA', country: 'INDIA', latitude: 18.5204, longitude: 73.8567 },
  { pincode: '411003', officeName: 'Pune Deccan Gymkhana', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Pune City East', regionName: 'Maharashtra', circleName: 'Maharashtra', taluk: 'Pune', district: 'Pune', state: 'MAHARASHTRA', country: 'INDIA', latitude: 18.5204, longitude: 73.8567 },
  { pincode: '411004', officeName: 'Pune Bhavani Peth', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Pune City East', regionName: 'Maharashtra', circleName: 'Maharashtra', taluk: 'Pune', district: 'Pune', state: 'MAHARASHTRA', country: 'INDIA', latitude: 18.5204, longitude: 73.8567 },
  { pincode: '411005', officeName: 'Pune Parvati', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Pune City East', regionName: 'Maharashtra', circleName: 'Maharashtra', taluk: 'Pune', district: 'Pune', state: 'MAHARASHTRA', country: 'INDIA', latitude: 18.5204, longitude: 73.8567 },

  // Surat
  { pincode: '395001', officeName: 'Surat GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Surat', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Surat', district: 'Surat', state: 'GUJARAT', country: 'INDIA', latitude: 21.1702, longitude: 72.8311 },
  { pincode: '395002', officeName: 'Surat Nanpura', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Surat', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Surat', district: 'Surat', state: 'GUJARAT', country: 'INDIA', latitude: 21.1702, longitude: 72.8311 },
  { pincode: '395003', officeName: 'Surat Athwa Lines', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Surat', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Surat', district: 'Surat', state: 'GUJARAT', country: 'INDIA', latitude: 21.1702, longitude: 72.8311 },
  { pincode: '395004', officeName: 'Surat Varachha Road', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Surat', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Surat', district: 'Surat', state: 'GUJARAT', country: 'INDIA', latitude: 21.1702, longitude: 72.8311 },
  { pincode: '395005', officeName: 'Surat Ring Road', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Surat', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Surat', district: 'Surat', state: 'GUJARAT', country: 'INDIA', latitude: 21.1702, longitude: 72.8311 },

  // Lucknow
  { pincode: '226001', officeName: 'Lucknow GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Lucknow City', regionName: 'Uttar Pradesh', circleName: 'Uttar Pradesh', taluk: 'Lucknow', district: 'Lucknow', state: 'UTTAR PRADESH', country: 'INDIA', latitude: 26.8467, longitude: 80.9462 },
  { pincode: '226002', officeName: 'Lucknow Husainganj', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Lucknow City', regionName: 'Uttar Pradesh', circleName: 'Uttar Pradesh', taluk: 'Lucknow', district: 'Lucknow', state: 'UTTAR PRADESH', country: 'INDIA', latitude: 26.8467, longitude: 80.9462 },
  { pincode: '226003', officeName: 'Lucknow Vikas Nagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Lucknow City', regionName: 'Uttar Pradesh', circleName: 'Uttar Pradesh', taluk: 'Lucknow', district: 'Lucknow', state: 'UTTAR PRADESH', country: 'INDIA', latitude: 26.8467, longitude: 80.9462 },
  { pincode: '226004', officeName: 'Lucknow Alambagh', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Lucknow City', regionName: 'Uttar Pradesh', circleName: 'Uttar Pradesh', taluk: 'Lucknow', district: 'Lucknow', state: 'UTTAR PRADESH', country: 'INDIA', latitude: 26.8467, longitude: 80.9462 },
  { pincode: '226005', officeName: 'Lucknow Gomti Nagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Lucknow City', regionName: 'Uttar Pradesh', circleName: 'Uttar Pradesh', taluk: 'Lucknow', district: 'Lucknow', state: 'UTTAR PRADESH', country: 'INDIA', latitude: 26.8467, longitude: 80.9462 },

  // Kanpur
  { pincode: '208001', officeName: 'Kanpur GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Kanpur City', regionName: 'Uttar Pradesh', circleName: 'Uttar Pradesh', taluk: 'Kanpur', district: 'Kanpur Nagar', state: 'UTTAR PRADESH', country: 'INDIA', latitude: 26.4499, longitude: 80.3319 },
  { pincode: '208002', officeName: 'Kanpur Civil Lines', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Kanpur City', regionName: 'Uttar Pradesh', circleName: 'Uttar Pradesh', taluk: 'Kanpur', district: 'Kanpur Nagar', state: 'UTTAR PRADESH', country: 'INDIA', latitude: 26.4499, longitude: 80.3319 },
  { pincode: '208003', officeName: 'Kanpur Kidwai Nagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Kanpur City', regionName: 'Uttar Pradesh', circleName: 'Uttar Pradesh', taluk: 'Kanpur', district: 'Kanpur Nagar', state: 'UTTAR PRADESH', country: 'INDIA', latitude: 26.4499, longitude: 80.3319 },
  { pincode: '208004', officeName: 'Kanpur Kakadeo', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Kanpur City', regionName: 'Uttar Pradesh', circleName: 'Uttar Pradesh', taluk: 'Kanpur', district: 'Kanpur Nagar', state: 'UTTAR PRADESH', country: 'INDIA', latitude: 26.4499, longitude: 80.3319 },
  { pincode: '208005', officeName: 'Kanpur Shyam Nagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Kanpur City', regionName: 'Uttar Pradesh', circleName: 'Uttar Pradesh', taluk: 'Kanpur', district: 'Kanpur Nagar', state: 'UTTAR PRADESH', country: 'INDIA', latitude: 26.4499, longitude: 80.3319 },

  // Nagpur
  { pincode: '440001', officeName: 'Nagpur GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Nagpur City', regionName: 'Maharashtra', circleName: 'Maharashtra', taluk: 'Nagpur', district: 'Nagpur', state: 'MAHARASHTRA', country: 'INDIA', latitude: 21.1458, longitude: 79.0882 },
  { pincode: '440002', officeName: 'Nagpur Itwari', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Nagpur City', regionName: 'Maharashtra', circleName: 'Maharashtra', taluk: 'Nagpur', district: 'Nagpur', state: 'MAHARASHTRA', country: 'INDIA', latitude: 21.1458, longitude: 79.0882 },
  { pincode: '440003', officeName: 'Nagpur Civil Lines', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Nagpur City', regionName: 'Maharashtra', circleName: 'Maharashtra', taluk: 'Nagpur', district: 'Nagpur', state: 'MAHARASHTRA', country: 'INDIA', latitude: 21.1458, longitude: 79.0882 },
  { pincode: '440004', officeName: 'Nagpur Sadar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Nagpur City', regionName: 'Maharashtra', circleName: 'Maharashtra', taluk: 'Nagpur', district: 'Nagpur', state: 'MAHARASHTRA', country: 'INDIA', latitude: 21.1458, longitude: 79.0882 },
  { pincode: '440005', officeName: 'Nagpur Dharampeth', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Nagpur City', regionName: 'Maharashtra', circleName: 'Maharashtra', taluk: 'Nagpur', district: 'Nagpur', state: 'MAHARASHTRA', country: 'INDIA', latitude: 21.1458, longitude: 79.0882 },

  // Indore
  { pincode: '452001', officeName: 'Indore GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Indore City', regionName: 'Madhya Pradesh', circleName: 'Madhya Pradesh', taluk: 'Indore', district: 'Indore', state: 'MADHYA PRADESH', country: 'INDIA', latitude: 22.7196, longitude: 75.8577 },
  { pincode: '452002', officeName: 'Indore Rajwada', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Indore City', regionName: 'Madhya Pradesh', circleName: 'Madhya Pradesh', taluk: 'Indore', district: 'Indore', state: 'MADHYA PRADESH', country: 'INDIA', latitude: 22.7196, longitude: 75.8577 },
  { pincode: '452003', officeName: 'Indore Khajrana', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Indore City', regionName: 'Madhya Pradesh', circleName: 'Madhya Pradesh', taluk: 'Indore', district: 'Indore', state: 'MADHYA PRADESH', country: 'INDIA', latitude: 22.7196, longitude: 75.8577 },
  { pincode: '452004', officeName: 'Indore Vijay Nagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Indore City', regionName: 'Madhya Pradesh', circleName: 'Madhya Pradesh', taluk: 'Indore', district: 'Indore', state: 'MADHYA PRADESH', country: 'INDIA', latitude: 22.7196, longitude: 75.8577 },
  { pincode: '452005', officeName: 'Indore Palasia', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Indore City', regionName: 'Madhya Pradesh', circleName: 'Madhya Pradesh', taluk: 'Indore', district: 'Indore', state: 'MADHYA PRADESH', country: 'INDIA', latitude: 22.7196, longitude: 75.8577 },

  // Bhopal
  { pincode: '462001', officeName: 'Bhopal GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Bhopal', regionName: 'Madhya Pradesh', circleName: 'Madhya Pradesh', taluk: 'Bhopal', district: 'Bhopal', state: 'MADHYA PRADESH', country: 'INDIA', latitude: 23.2599, longitude: 77.4126 },
  { pincode: '462002', officeName: 'Bhopal TT Nagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Bhopal', regionName: 'Madhya Pradesh', circleName: 'Madhya Pradesh', taluk: 'Bhopal', district: 'Bhopal', state: 'MADHYA PRADESH', country: 'INDIA', latitude: 23.2599, longitude: 77.4126 },
  { pincode: '462003', officeName: 'Bhopal Arera Colony', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Bhopal', regionName: 'Madhya Pradesh', circleName: 'Madhya Pradesh', taluk: 'Bhopal', district: 'Bhopal', state: 'MADHYA PRADESH', country: 'INDIA', latitude: 23.2599, longitude: 77.4126 },
  { pincode: '462004', officeName: 'Bhopal MP Nagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Bhopal', regionName: 'Madhya Pradesh', circleName: 'Madhya Pradesh', taluk: 'Bhopal', district: 'Bhopal', state: 'MADHYA PRADESH', country: 'INDIA', latitude: 23.2599, longitude: 77.4126 },
  { pincode: '462005', officeName: 'Bhopal Kolar Road', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Bhopal', regionName: 'Madhya Pradesh', circleName: 'Madhya Pradesh', taluk: 'Bhopal', district: 'Bhopal', state: 'MADHYA PRADESH', country: 'INDIA', latitude: 23.2599, longitude: 77.4126 },

  // Patna
  { pincode: '800001', officeName: 'Patna GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Patna', regionName: 'Bihar', circleName: 'Bihar', taluk: 'Patna', district: 'Patna', state: 'BIHAR', country: 'INDIA', latitude: 25.5941, longitude: 85.1376 },
  { pincode: '800002', officeName: 'Patna City', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Patna', regionName: 'Bihar', circleName: 'Bihar', taluk: 'Patna', district: 'Patna', state: 'BIHAR', country: 'INDIA', latitude: 25.5941, longitude: 85.1376 },
  { pincode: '800003', officeName: 'Patna Rajabazar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Patna', regionName: 'Bihar', circleName: 'Bihar', taluk: 'Patna', district: 'Patna', state: 'BIHAR', country: 'INDIA', latitude: 25.5941, longitude: 85.1376 },
  { pincode: '800004', officeName: 'Patna Kankerbagh', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Patna', regionName: 'Bihar', circleName: 'Bihar', taluk: 'Patna', district: 'Patna', state: 'BIHAR', country: 'INDIA', latitude: 25.5941, longitude: 85.1376 },
  { pincode: '800005', officeName: 'Patna Gulzarbagh', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Patna', regionName: 'Bihar', circleName: 'Bihar', taluk: 'Patna', district: 'Patna', state: 'BIHAR', country: 'INDIA', latitude: 25.5941, longitude: 85.1376 },

  // Vadodara
  { pincode: '390001', officeName: 'Vadodara GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Vadodara West', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Vadodara', district: 'Vadodara', state: 'GUJARAT', country: 'INDIA', latitude: 22.3072, longitude: 73.1812 },
  { pincode: '390002', officeName: 'Vadodara Raopura', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Vadodara West', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Vadodara', district: 'Vadodara', state: 'GUJARAT', country: 'INDIA', latitude: 22.3072, longitude: 73.1812 },
  { pincode: '390003', officeName: 'Vadodara Alkapuri', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Vadodara West', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Vadodara', district: 'Vadodara', state: 'GUJARAT', country: 'INDIA', latitude: 22.3072, longitude: 73.1812 },
  { pincode: '390004', officeName: 'Vadodara Karelibaug', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Vadodara West', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Vadodara', district: 'Vadodara', state: 'GUJARAT', country: 'INDIA', latitude: 22.3072, longitude: 73.1812 },
  { pincode: '390005', officeName: 'Vadodara Gotri', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Vadodara West', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Vadodara', district: 'Vadodara', state: 'GUJARAT', country: 'INDIA', latitude: 22.3072, longitude: 73.1812 },

  // Coimbatore
  { pincode: '641001', officeName: 'Coimbatore', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Coimbatore', regionName: 'Tamilnadu', circleName: 'Tamilnadu', taluk: 'Coimbatore North', district: 'Coimbatore', state: 'TAMIL NADU', country: 'INDIA', latitude: 11.0168, longitude: 76.9558 },
  { pincode: '641002', officeName: 'Coimbatore Town Hall', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Coimbatore', regionName: 'Tamilnadu', circleName: 'Tamilnadu', taluk: 'Coimbatore North', district: 'Coimbatore', state: 'TAMIL NADU', country: 'INDIA', latitude: 11.0168, longitude: 76.9558 },
  { pincode: '641003', officeName: 'Coimbatore R.S. Puram', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Coimbatore', regionName: 'Tamilnadu', circleName: 'Tamilnadu', taluk: 'Coimbatore North', district: 'Coimbatore', state: 'TAMIL NADU', country: 'INDIA', latitude: 11.0168, longitude: 76.9558 },
  { pincode: '641004', officeName: 'Coimbatore Peelamedu', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Coimbatore', regionName: 'Tamilnadu', circleName: 'Tamilnadu', taluk: 'Coimbatore North', district: 'Coimbatore', state: 'TAMIL NADU', country: 'INDIA', latitude: 11.0168, longitude: 76.9558 },
  { pincode: '641005', officeName: 'Coimbatore Gandhipuram', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Coimbatore', regionName: 'Tamilnadu', circleName: 'Tamilnadu', taluk: 'Coimbatore North', district: 'Coimbatore', state: 'TAMIL NADU', country: 'INDIA', latitude: 11.0168, longitude: 76.9558 },

  // Visakhapatnam
  { pincode: '530001', officeName: 'Visakhapatnam', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Visakhapatnam', regionName: 'Andhra Pradesh', circleName: 'Andhra Pradesh', taluk: 'Visakhapatnam', district: 'Visakhapatnam', state: 'ANDHRA PRADESH', country: 'INDIA', latitude: 17.6868, longitude: 83.2185 },
  { pincode: '530002', officeName: 'Visakhapatnam Daba Gardens', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Visakhapatnam', regionName: 'Andhra Pradesh', circleName: 'Andhra Pradesh', taluk: 'Visakhapatnam', district: 'Visakhapatnam', state: 'ANDHRA PRADESH', country: 'INDIA', latitude: 17.6868, longitude: 83.2185 },
  { pincode: '530003', officeName: 'Visakhapatnam Dwaraka Nagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Visakhapatnam', regionName: 'Andhra Pradesh', circleName: 'Andhra Pradesh', taluk: 'Visakhapatnam', district: 'Visakhapatnam', state: 'ANDHRA PRADESH', country: 'INDIA', latitude: 17.6868, longitude: 83.2185 },
  { pincode: '530004', officeName: 'Visakhapatnam MVP Colony', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Visakhapatnam', regionName: 'Andhra Pradesh', circleName: 'Andhra Pradesh', taluk: 'Visakhapatnam', district: 'Visakhapatnam', state: 'ANDHRA PRADESH', country: 'INDIA', latitude: 17.6868, longitude: 83.2185 },
  { pincode: '530005', officeName: 'Visakhapatnam Siripuram', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Visakhapatnam', regionName: 'Andhra Pradesh', circleName: 'Andhra Pradesh', taluk: 'Visakhapatnam', district: 'Visakhapatnam', state: 'ANDHRA PRADESH', country: 'INDIA', latitude: 17.6868, longitude: 83.2185 },

  // Vijayawada
  { pincode: '520001', officeName: 'Vijayawada', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Vijayawada', regionName: 'Andhra Pradesh', circleName: 'Andhra Pradesh', taluk: 'Vijayawada', district: 'Krishna', state: 'ANDHRA PRADESH', country: 'INDIA', latitude: 16.5062, longitude: 80.6480 },
  { pincode: '520002', officeName: 'Vijayawada Gandhi Nagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Vijayawada', regionName: 'Andhra Pradesh', circleName: 'Andhra Pradesh', taluk: 'Vijayawada', district: 'Krishna', state: 'ANDHRA PRADESH', country: 'INDIA', latitude: 16.5062, longitude: 80.6480 },
  { pincode: '520003', officeName: 'Vijayawada Suryaraopet', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Vijayawada', regionName: 'Andhra Pradesh', circleName: 'Andhra Pradesh', taluk: 'Vijayawada', district: 'Krishna', state: 'ANDHRA PRADESH', country: 'INDIA', latitude: 16.5062, longitude: 80.6480 },
  { pincode: '520004', officeName: 'Vijayawada Bhavanipuram', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Vijayawada', regionName: 'Andhra Pradesh', circleName: 'Andhra Pradesh', taluk: 'Vijayawada', district: 'Krishna', state: 'ANDHRA PRADESH', country: 'INDIA', latitude: 16.5062, longitude: 80.6480 },
  { pincode: '520005', officeName: 'Vijayawada Ramavarappadu', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Vijayawada', regionName: 'Andhra Pradesh', circleName: 'Andhra Pradesh', taluk: 'Vijayawada', district: 'Krishna', state: 'ANDHRA PRADESH', country: 'INDIA', latitude: 16.5062, longitude: 80.6480 },

  // Guwahati
  { pincode: '781001', officeName: 'Guwahati GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Guwahati', regionName: 'Assam', circleName: 'Assam', taluk: 'Guwahati', district: 'Kamrup Metropolitan', state: 'ASSAM', country: 'INDIA', latitude: 26.1445, longitude: 91.7362 },
  { pincode: '781002', officeName: 'Guwahati Paltan Bazar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Guwahati', regionName: 'Assam', circleName: 'Assam', taluk: 'Guwahati', district: 'Kamrup Metropolitan', state: 'ASSAM', country: 'INDIA', latitude: 26.1445, longitude: 91.7362 },
  { pincode: '781003', officeName: 'Guwahati Rehabari', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Guwahati', regionName: 'Assam', circleName: 'Assam', taluk: 'Guwahati', district: 'Kamrup Metropolitan', state: 'ASSAM', country: 'INDIA', latitude: 26.1445, longitude: 91.7362 },
  { pincode: '781004', officeName: 'Guwahati Zoo Road', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Guwahati', regionName: 'Assam', circleName: 'Assam', taluk: 'Guwahati', district: 'Kamrup Metropolitan', state: 'ASSAM', country: 'INDIA', latitude: 26.1445, longitude: 91.7362 },
  { pincode: '781005', officeName: 'Guwahati Pan Bazar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Guwahati', regionName: 'Assam', circleName: 'Assam', taluk: 'Guwahati', district: 'Kamrup Metropolitan', state: 'ASSAM', country: 'INDIA', latitude: 26.1445, longitude: 91.7362 },

  // Chandigarh
  { pincode: '160001', officeName: 'Chandigarh GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Chandigarh', regionName: 'Punjab', circleName: 'Punjab', taluk: 'Chandigarh', district: 'Chandigarh', state: 'CHANDIGARH', country: 'INDIA', latitude: 30.7333, longitude: 76.7794 },
  { pincode: '160002', officeName: 'Chandigarh Sector 17', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Chandigarh', regionName: 'Punjab', circleName: 'Punjab', taluk: 'Chandigarh', district: 'Chandigarh', state: 'CHANDIGARH', country: 'INDIA', latitude: 30.7333, longitude: 76.7794 },
  { pincode: '160003', officeName: 'Chandigarh Sector 22', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Chandigarh', regionName: 'Punjab', circleName: 'Punjab', taluk: 'Chandigarh', district: 'Chandigarh', state: 'CHANDIGARH', country: 'INDIA', latitude: 30.7333, longitude: 76.7794 },
  { pincode: '160004', officeName: 'Chandigarh Sector 15', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Chandigarh', regionName: 'Punjab', circleName: 'Punjab', taluk: 'Chandigarh', district: 'Chandigarh', state: 'CHANDIGARH', country: 'INDIA', latitude: 30.7333, longitude: 76.7794 },
  { pincode: '160005', officeName: 'Chandigarh Sector 11', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Chandigarh', regionName: 'Punjab', circleName: 'Punjab', taluk: 'Chandigarh', district: 'Chandigarh', state: 'CHANDIGARH', country: 'INDIA', latitude: 30.7333, longitude: 76.7794 },

  // Jammu
  { pincode: '180001', officeName: 'Jammu GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Jammu', regionName: 'Jammu and Kashmir', circleName: 'Jammu and Kashmir', taluk: 'Jammu', district: 'Jammu', state: 'JAMMU AND KASHMIR', country: 'INDIA', latitude: 32.7266, longitude: 74.8570 },
  { pincode: '180002', officeName: 'Jammu Trikuta Nagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Jammu', regionName: 'Jammu and Kashmir', circleName: 'Jammu and Kashmir', taluk: 'Jammu', district: 'Jammu', state: 'JAMMU AND KASHMIR', country: 'INDIA', latitude: 32.7266, longitude: 74.8570 },
  { pincode: '180003', officeName: 'Jammu Gandhi Nagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Jammu', regionName: 'Jammu and Kashmir', circleName: 'Jammu and Kashmir', taluk: 'Jammu', district: 'Jammu', state: 'JAMMU AND KASHMIR', country: 'INDIA', latitude: 32.7266, longitude: 74.8570 },
  { pincode: '180004', officeName: 'Jammu Channi Himmat', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Jammu', regionName: 'Jammu and Kashmir', circleName: 'Jammu and Kashmir', taluk: 'Jammu', district: 'Jammu', state: 'JAMMU AND KASHMIR', country: 'INDIA', latitude: 32.7266, longitude: 74.8570 },
  { pincode: '180005', officeName: 'Jammu Bakshi Nagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Jammu', regionName: 'Jammu and Kashmir', circleName: 'Jammu and Kashmir', taluk: 'Jammu', district: 'Jammu', state: 'JAMMU AND KASHMIR', country: 'INDIA', latitude: 32.7266, longitude: 74.8570 },

  // Ranchi
  { pincode: '834001', officeName: 'Ranchi GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Ranchi', regionName: 'Jharkhand', circleName: 'Jharkhand', taluk: 'Ranchi', district: 'Ranchi', state: 'JHARKHAND', country: 'INDIA', latitude: 23.3441, longitude: 85.3096 },
  { pincode: '834002', officeName: 'Ranchi HEC', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Ranchi', regionName: 'Jharkhand', circleName: 'Jharkhand', taluk: 'Ranchi', district: 'Ranchi', state: 'JHARKHAND', country: 'INDIA', latitude: 23.3441, longitude: 85.3096 },
  { pincode: '834003', officeName: 'Ranchi Lalpur', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Ranchi', regionName: 'Jharkhand', circleName: 'Jharkhand', taluk: 'Ranchi', district: 'Ranchi', state: 'JHARKHAND', country: 'INDIA', latitude: 23.3441, longitude: 85.3096 },
  { pincode: '834004', officeName: 'Ranchi Kanke Road', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Ranchi', regionName: 'Jharkhand', circleName: 'Jharkhand', taluk: 'Ranchi', district: 'Ranchi', state: 'JHARKHAND', country: 'INDIA', latitude: 23.3441, longitude: 85.3096 },
  { pincode: '834005', officeName: 'Ranchi Doranda', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Ranchi', regionName: 'Jharkhand', circleName: 'Jharkhand', taluk: 'Ranchi', district: 'Ranchi', state: 'JHARKHAND', country: 'INDIA', latitude: 23.3441, longitude: 85.3096 },

  // Raipur
  { pincode: '492001', officeName: 'Raipur GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Raipur', regionName: 'Chhattisgarh', circleName: 'Chhattisgarh', taluk: 'Raipur', district: 'Raipur', state: 'CHHATTISGARH', country: 'INDIA', latitude: 21.2514, longitude: 81.6296 },
  { pincode: '492002', officeName: 'Raipur Pandri', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Raipur', regionName: 'Chhattisgarh', circleName: 'Chhattisgarh', taluk: 'Raipur', district: 'Raipur', state: 'CHHATTISGARH', country: 'INDIA', latitude: 21.2514, longitude: 81.6296 },
  { pincode: '492003', officeName: 'Raipur Shatabdi Nagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Raipur', regionName: 'Chhattisgarh', circleName: 'Chhattisgarh', taluk: 'Raipur', district: 'Raipur', state: 'CHHATTISGARH', country: 'INDIA', latitude: 21.2514, longitude: 81.6296 },
  { pincode: '492004', officeName: 'Raipur Civil Lines', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Raipur', regionName: 'Chhattisgarh', circleName: 'Chhattisgarh', taluk: 'Raipur', district: 'Raipur', state: 'CHHATTISGARH', country: 'INDIA', latitude: 21.2514, longitude: 81.6296 },
  { pincode: '492005', officeName: 'Raipur Byron Bazar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Raipur', regionName: 'Chhattisgarh', circleName: 'Chhattisgarh', taluk: 'Raipur', district: 'Raipur', state: 'CHHATTISGARH', country: 'INDIA', latitude: 21.2514, longitude: 81.6296 },

  // Dehradun
  { pincode: '248001', officeName: 'Dehradun GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Dehradun', regionName: 'Uttarakhand', circleName: 'Uttarakhand', taluk: 'Dehradun', district: 'Dehradun', state: 'UTTARAKHAND', country: 'INDIA', latitude: 30.3165, longitude: 78.0322 },
  { pincode: '248002', officeName: 'Dehradun Cantt', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Dehradun', regionName: 'Uttarakhand', circleName: 'Uttarakhand', taluk: 'Dehradun', district: 'Dehradun', state: 'UTTARAKHAND', country: 'INDIA', latitude: 30.3165, longitude: 78.0322 },
  { pincode: '248003', officeName: 'Dehradun Rajpur Road', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Dehradun', regionName: 'Uttarakhand', circleName: 'Uttarakhand', taluk: 'Dehradun', district: 'Dehradun', state: 'UTTARAKHAND', country: 'INDIA', latitude: 30.3165, longitude: 78.0322 },
  { pincode: '248004', officeName: 'Dehradun Nehru Colony', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Dehradun', regionName: 'Uttarakhand', circleName: 'Uttarakhand', taluk: 'Dehradun', district: 'Dehradun', state: 'UTTARAKHAND', country: 'INDIA', latitude: 30.3165, longitude: 78.0322 },
  { pincode: '248005', officeName: 'Dehradun Race Course', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Dehradun', regionName: 'Uttarakhand', circleName: 'Uttarakhand', taluk: 'Dehradun', district: 'Dehradun', state: 'UTTARAKHAND', country: 'INDIA', latitude: 30.3165, longitude: 78.0322 },

  // Shimla
  { pincode: '171001', officeName: 'Shimla GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Shimla', regionName: 'Himachal Pradesh', circleName: 'Himachal Pradesh', taluk: 'Shimla', district: 'Shimla', state: 'HIMACHAL PRADESH', country: 'INDIA', latitude: 31.1048, longitude: 77.1734 },
  { pincode: '171002', officeName: 'Shimla Kasumpti', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Shimla', regionName: 'Himachal Pradesh', circleName: 'Himachal Pradesh', taluk: 'Shimla', district: 'Shimla', state: 'HIMACHAL PRADESH', country: 'INDIA', latitude: 31.1048, longitude: 77.1734 },
  { pincode: '171003', officeName: 'Shimla Chotta Shimla', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Shimla', regionName: 'Himachal Pradesh', circleName: 'Himachal Pradesh', taluk: 'Shimla', district: 'Shimla', state: 'HIMACHAL PRADESH', country: 'INDIA', latitude: 31.1048, longitude: 77.1734 },
  { pincode: '171004', officeName: 'Shimla Summer Hill', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Shimla', regionName: 'Himachal Pradesh', circleName: 'Himachal Pradesh', taluk: 'Shimla', district: 'Shimla', state: 'HIMACHAL PRADESH', country: 'INDIA', latitude: 31.1048, longitude: 77.1734 },
  { pincode: '171005', officeName: 'Shimla New Shimla', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Shimla', regionName: 'Himachal Pradesh', circleName: 'Himachal Pradesh', taluk: 'Shimla', district: 'Shimla', state: 'HIMACHAL PRADESH', country: 'INDIA', latitude: 31.1048, longitude: 77.1734 },

  // Thiruvananthapuram
  { pincode: '695001', officeName: 'Thiruvananthapuram GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Thiruvananthapuram North', regionName: 'Kerala', circleName: 'Kerala', taluk: 'Thiruvananthapuram', district: 'Thiruvananthapuram', state: 'KERALA', country: 'INDIA', latitude: 8.5241, longitude: 76.9366 },
  { pincode: '695002', officeName: 'Thiruvananthapuram Fort', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Thiruvananthapuram North', regionName: 'Kerala', circleName: 'Kerala', taluk: 'Thiruvananthapuram', district: 'Thiruvananthapuram', state: 'KERALA', country: 'INDIA', latitude: 8.5241, longitude: 76.9366 },
  { pincode: '695003', officeName: 'Thiruvananthapuram Medical College', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Thiruvananthapuram North', regionName: 'Kerala', circleName: 'Kerala', taluk: 'Thiruvananthapuram', district: 'Thiruvananthapuram', state: 'KERALA', country: 'INDIA', latitude: 8.5241, longitude: 76.9366 },
  { pincode: '695004', officeName: 'Thiruvananthapuram Statue', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Thiruvananthapuram North', regionName: 'Kerala', circleName: 'Kerala', taluk: 'Thiruvananthapuram', district: 'Thiruvananthapuram', state: 'KERALA', country: 'INDIA', latitude: 8.5241, longitude: 76.9366 },
  { pincode: '695005', officeName: 'Thiruvananthapuram Kowdiar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Thiruvananthapuram North', regionName: 'Kerala', circleName: 'Kerala', taluk: 'Thiruvananthapuram', district: 'Thiruvananthapuram', state: 'KERALA', country: 'INDIA', latitude: 8.5241, longitude: 76.9366 },

  // Bhubaneswar
  { pincode: '751001', officeName: 'Bhubaneswar GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Bhubaneswar', regionName: 'Orissa', circleName: 'Orissa', taluk: 'Bhubaneswar', district: 'Khordha', state: 'ODISHA', country: 'INDIA', latitude: 20.2961, longitude: 85.8245 },
  { pincode: '751002', officeName: 'Bhubaneswar BJB Nagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Bhubaneswar', regionName: 'Orissa', circleName: 'Orissa', taluk: 'Bhubaneswar', district: 'Khordha', state: 'ODISHA', country: 'INDIA', latitude: 20.2961, longitude: 85.8245 },
  { pincode: '751003', officeName: 'Bhubaneswar Sahid Nagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Bhubaneswar', regionName: 'Orissa', circleName: 'Orissa', taluk: 'Bhubaneswar', district: 'Khordha', state: 'ODISHA', country: 'INDIA', latitude: 20.2961, longitude: 85.8245 },
  { pincode: '751004', officeName: 'Bhubaneswar Nayapalli', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Bhubaneswar', regionName: 'Orissa', circleName: 'Orissa', taluk: 'Bhubaneswar', district: 'Khordha', state: 'ODISHA', country: 'INDIA', latitude: 20.2961, longitude: 85.8245 },
  { pincode: '751005', officeName: 'Bhubaneswar Unit 9', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Bhubaneswar', regionName: 'Orissa', circleName: 'Orissa', taluk: 'Bhubaneswar', district: 'Khordha', state: 'ODISHA', country: 'INDIA', latitude: 20.2961, longitude: 85.8245 },

  // Gangtok
  { pincode: '737101', officeName: 'Gangtok HPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Sikkim', regionName: 'North Bengal And Sikkim', circleName: 'West Bengal', taluk: 'Gangtok', district: 'East Sikkim', state: 'SIKKIM', country: 'INDIA', latitude: 27.3389, longitude: 88.6065 },
  { pincode: '737102', officeName: 'Gangtok Bazar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Sikkim', regionName: 'North Bengal And Sikkim', circleName: 'West Bengal', taluk: 'Gangtok', district: 'East Sikkim', state: 'SIKKIM', country: 'INDIA', latitude: 27.3389, longitude: 88.6065 },
  { pincode: '737103', officeName: 'Gangtok Deorali', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Sikkim', regionName: 'North Bengal And Sikkim', circleName: 'West Bengal', taluk: 'Gangtok', district: 'East Sikkim', state: 'SIKKIM', country: 'INDIA', latitude: 27.3389, longitude: 88.6065 },
  { pincode: '737104', officeName: 'Gangtok Tadong', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Sikkim', regionName: 'North Bengal And Sikkim', circleName: 'West Bengal', taluk: 'Gangtok', district: 'East Sikkim', state: 'SIKKIM', country: 'INDIA', latitude: 27.3389, longitude: 88.6065 },
  { pincode: '737105', officeName: 'Gangtok Arithang', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Sikkim', regionName: 'North Bengal And Sikkim', circleName: 'West Bengal', taluk: 'Gangtok', district: 'East Sikkim', state: 'SIKKIM', country: 'INDIA', latitude: 27.3389, longitude: 88.6065 },

  // Port Blair
  { pincode: '744101', officeName: 'Port Blair H.O', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'A & N Islands', regionName: 'North East', circleName: 'West Bengal', taluk: 'Port Blair', district: 'South Andaman', state: 'ANDAMAN AND NICOBAR ISLANDS', country: 'INDIA', latitude: 11.6234, longitude: 92.7265 },
  { pincode: '744102', officeName: 'Port Blair Aberdeen Bazar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'A & N Islands', regionName: 'North East', circleName: 'West Bengal', taluk: 'Port Blair', district: 'South Andaman', state: 'ANDAMAN AND NICOBAR ISLANDS', country: 'INDIA', latitude: 11.6234, longitude: 92.7265 },
  { pincode: '744103', officeName: 'Port Blair Junglighat', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'A & N Islands', regionName: 'North East', circleName: 'West Bengal', taluk: 'Port Blair', district: 'South Andaman', state: 'ANDAMAN AND NICOBAR ISLANDS', country: 'INDIA', latitude: 11.6234, longitude: 92.7265 },
  { pincode: '744104', officeName: 'Port Blair Delanipur', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'A & N Islands', regionName: 'North East', circleName: 'West Bengal', taluk: 'Port Blair', district: 'South Andaman', state: 'ANDAMAN AND NICOBAR ISLANDS', country: 'INDIA', latitude: 11.6234, longitude: 92.7265 },
  { pincode: '744105', officeName: 'Port Blair Haddo', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'A & N Islands', regionName: 'North East', circleName: 'West Bengal', taluk: 'Port Blair', district: 'South Andaman', state: 'ANDAMAN AND NICOBAR ISLANDS', country: 'INDIA', latitude: 11.6234, longitude: 92.7265 },

  // Panaji
  { pincode: '403001', officeName: 'Panaji H.O', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Goa', regionName: 'Goa-Panaji', circleName: 'Maharashtra', taluk: 'Tiswadi', district: 'North Goa', state: 'GOA', country: 'INDIA', latitude: 15.4909, longitude: 73.8278 },
  { pincode: '403002', officeName: 'Panaji Fontainhas', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Goa', regionName: 'Goa-Panaji', circleName: 'Maharashtra', taluk: 'Tiswadi', district: 'North Goa', state: 'GOA', country: 'INDIA', latitude: 15.4909, longitude: 73.8278 },
  { pincode: '403003', officeName: 'Panaji Campal', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Goa', regionName: 'Goa-Panaji', circleName: 'Maharashtra', taluk: 'Tiswadi', district: 'North Goa', state: 'GOA', country: 'INDIA', latitude: 15.4909, longitude: 73.8278 },
  { pincode: '403004', officeName: 'Panaji Altinho', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Goa', regionName: 'Goa-Panaji', circleName: 'Maharashtra', taluk: 'Tiswadi', district: 'North Goa', state: 'GOA', country: 'INDIA', latitude: 15.4909, longitude: 73.8278 },
  { pincode: '403005', officeName: 'Panaji St Inez', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Goa', regionName: 'Goa-Panaji', circleName: 'Maharashtra', taluk: 'Tiswadi', district: 'North Goa', state: 'GOA', country: 'INDIA', latitude: 15.4909, longitude: 73.8278 },

  // Agartala
  { pincode: '799001', officeName: 'Agartala H.O', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Agartala', regionName: 'North East', circleName: 'North Eastern', taluk: 'Agartala', district: 'West Tripura', state: 'TRIPURA', country: 'INDIA', latitude: 23.8315, longitude: 91.2868 },
  { pincode: '799002', officeName: 'Agartala Udaipur', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Agartala', regionName: 'North East', circleName: 'North Eastern', taluk: 'Agartala', district: 'West Tripura', state: 'TRIPURA', country: 'INDIA', latitude: 23.8315, longitude: 91.2868 },
  { pincode: '799003', officeName: 'Agartala Kunjaban', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Agartala', regionName: 'North East', circleName: 'North Eastern', taluk: 'Agartala', district: 'West Tripura', state: 'TRIPURA', country: 'INDIA', latitude: 23.8315, longitude: 91.2868 },
  { pincode: '799004', officeName: 'Agartala Banamalipur', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Agartala', regionName: 'North East', circleName: 'North Eastern', taluk: 'Agartala', district: 'West Tripura', state: 'TRIPURA', country: 'INDIA', latitude: 23.8315, longitude: 91.2868 },
  { pincode: '799005', officeName: 'Agartala Indranagar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Agartala', regionName: 'North East', circleName: 'North Eastern', taluk: 'Agartala', district: 'West Tripura', state: 'TRIPURA', country: 'INDIA', latitude: 23.8315, longitude: 91.2868 },

  // Aizawl
  { pincode: '796001', officeName: 'Aizawl H.O', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Mizoram', regionName: 'North East', circleName: 'North Eastern', taluk: 'Aizawl', district: 'Aizawl', state: 'MIZORAM', country: 'INDIA', latitude: 23.7271, longitude: 92.7176 },
  { pincode: '796002', officeName: 'Aizawl Dawrpui', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Mizoram', regionName: 'North East', circleName: 'North Eastern', taluk: 'Aizawl', district: 'Aizawl', state: 'MIZORAM', country: 'INDIA', latitude: 23.7271, longitude: 92.7176 },
  { pincode: '796003', officeName: 'Aizawl Tuikhuahtlang', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Mizoram', regionName: 'North East', circleName: 'North Eastern', taluk: 'Aizawl', district: 'Aizawl', state: 'MIZORAM', country: 'INDIA', latitude: 23.7271, longitude: 92.7176 },
  { pincode: '796004', officeName: 'Aizawl Chaltlang', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Mizoram', regionName: 'North East', circleName: 'North Eastern', taluk: 'Aizawl', district: 'Aizawl', state: 'MIZORAM', country: 'INDIA', latitude: 23.7271, longitude: 92.7176 },
  { pincode: '796005', officeName: 'Aizawl Zemabawk', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Mizoram', regionName: 'North East', circleName: 'North Eastern', taluk: 'Aizawl', district: 'Aizawl', state: 'MIZORAM', country: 'INDIA', latitude: 23.7271, longitude: 92.7176 },

  // Kohima
  { pincode: '797001', officeName: 'Kohima H.O', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Nagaland', regionName: 'North East', circleName: 'North Eastern', taluk: 'Kohima Sadar', district: 'Kohima', state: 'NAGALAND', country: 'INDIA', latitude: 25.6747, longitude: 94.1100 },
  { pincode: '797002', officeName: 'Kohima New Secretariat', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Nagaland', regionName: 'North East', circleName: 'North Eastern', taluk: 'Kohima Sadar', district: 'Kohima', state: 'NAGALAND', country: 'INDIA', latitude: 25.6747, longitude: 94.1100 },
  { pincode: '797003', officeName: 'Kohima High School', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Nagaland', regionName: 'North East', circleName: 'North Eastern', taluk: 'Kohima Sadar', district: 'Kohima', state: 'NAGALAND', country: 'INDIA', latitude: 25.6747, longitude: 94.1100 },
  { pincode: '797004', officeName: 'Kohima Midland', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Nagaland', regionName: 'North East', circleName: 'North Eastern', taluk: 'Kohima Sadar', district: 'Kohima', state: 'NAGALAND', country: 'INDIA', latitude: 25.6747, longitude: 94.1100 },
  { pincode: '797005', officeName: 'Kohima Lerie', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Nagaland', regionName: 'North East', circleName: 'North Eastern', taluk: 'Kohima Sadar', district: 'Kohima', state: 'NAGALAND', country: 'INDIA', latitude: 25.6747, longitude: 94.1100 },

  // Itanagar
  { pincode: '791111', officeName: 'Itanagar H.O', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Arunachal Pradesh', regionName: 'North East', circleName: 'North Eastern', taluk: 'Itanagar', district: 'Papum Pare', state: 'ARUNACHAL PRADESH', country: 'INDIA', latitude: 27.0844, longitude: 93.6053 },
  { pincode: '791112', officeName: 'Itanagar G Extension', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Arunachal Pradesh', regionName: 'North East', circleName: 'North Eastern', taluk: 'Itanagar', district: 'Papum Pare', state: 'ARUNACHAL PRADESH', country: 'INDIA', latitude: 27.0844, longitude: 93.6053 },
  { pincode: '791113', officeName: 'Itanagar Chimpu', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Arunachal Pradesh', regionName: 'North East', circleName: 'North Eastern', taluk: 'Itanagar', district: 'Papum Pare', state: 'ARUNACHAL PRADESH', country: 'INDIA', latitude: 27.0844, longitude: 93.6053 },
  { pincode: '791114', officeName: 'Itanagar Lekhi', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Arunachal Pradesh', regionName: 'North East', circleName: 'North Eastern', taluk: 'Itanagar', district: 'Papum Pare', state: 'ARUNACHAL PRADESH', country: 'INDIA', latitude: 27.0844, longitude: 93.6053 },
  { pincode: '791115', officeName: 'Itanagar Nirjuli', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Arunachal Pradesh', regionName: 'North East', circleName: 'North Eastern', taluk: 'Itanagar', district: 'Papum Pare', state: 'ARUNACHAL PRADESH', country: 'INDIA', latitude: 27.0844, longitude: 93.6053 },

  // Shillong
  { pincode: '793001', officeName: 'Shillong GPO', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Meghalaya', regionName: 'North East', circleName: 'North Eastern', taluk: 'Shillong', district: 'East Khasi Hills', state: 'MEGHALAYA', country: 'INDIA', latitude: 25.5788, longitude: 91.8933 },
  { pincode: '793002', officeName: 'Shillong Laitumkhrah', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Meghalaya', regionName: 'North East', circleName: 'North Eastern', taluk: 'Shillong', district: 'East Khasi Hills', state: 'MEGHALAYA', country: 'INDIA', latitude: 25.5788, longitude: 91.8933 },
  { pincode: '793003', officeName: 'Shillong Police Bazar', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Meghalaya', regionName: 'North East', circleName: 'North Eastern', taluk: 'Shillong', district: 'East Khasi Hills', state: 'MEGHALAYA', country: 'INDIA', latitude: 25.5788, longitude: 91.8933 },
  { pincode: '793004', officeName: 'Shillong Mawlai', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Meghalaya', regionName: 'North East', circleName: 'North Eastern', taluk: 'Shillong', district: 'East Khasi Hills', state: 'MEGHALAYA', country: 'INDIA', latitude: 25.5788, longitude: 91.8933 },
  { pincode: '793005', officeName: 'Shillong Nongthymmai', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Meghalaya', regionName: 'North East', circleName: 'North Eastern', taluk: 'Shillong', district: 'East Khasi Hills', state: 'MEGHALAYA', country: 'INDIA', latitude: 25.5788, longitude: 91.8933 },

  // Imphal
  { pincode: '795001', officeName: 'Imphal H.O', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Manipur', regionName: 'North East', circleName: 'North Eastern', taluk: 'Imphal West', district: 'Imphal West', state: 'MANIPUR', country: 'INDIA', latitude: 24.8170, longitude: 93.9368 },
  { pincode: '795002', officeName: 'Imphal Lamphelpat', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Manipur', regionName: 'North East', circleName: 'North Eastern', taluk: 'Imphal West', district: 'Imphal West', state: 'MANIPUR', country: 'INDIA', latitude: 24.8170, longitude: 93.9368 },
  { pincode: '795003', officeName: 'Imphal Uripok', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Manipur', regionName: 'North East', circleName: 'North Eastern', taluk: 'Imphal West', district: 'Imphal West', state: 'MANIPUR', country: 'INDIA', latitude: 24.8170, longitude: 93.9368 },
  { pincode: '795004', officeName: 'Imphal Porompat', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Manipur', regionName: 'North East', circleName: 'North Eastern', taluk: 'Imphal East', district: 'Imphal East', state: 'MANIPUR', country: 'INDIA', latitude: 24.8170, longitude: 93.9368 },
  { pincode: '795005', officeName: 'Imphal Singjamei', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Manipur', regionName: 'North East', circleName: 'North Eastern', taluk: 'Imphal West', district: 'Imphal West', state: 'MANIPUR', country: 'INDIA', latitude: 24.8170, longitude: 93.9368 },

  // Dispur
  { pincode: '781005', officeName: 'Dispur H.O', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Guwahati', regionName: 'Assam', circleName: 'Assam', taluk: 'Dispur', district: 'Kamrup Metropolitan', state: 'ASSAM', country: 'INDIA', latitude: 26.1433, longitude: 91.7898 },
  { pincode: '781006', officeName: 'Dispur Beltola', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Guwahati', regionName: 'Assam', circleName: 'Assam', taluk: 'Dispur', district: 'Kamrup Metropolitan', state: 'ASSAM', country: 'INDIA', latitude: 26.1433, longitude: 91.7898 },
  { pincode: '781007', officeName: 'Dispur Khanapara', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Guwahati', regionName: 'Assam', circleName: 'Assam', taluk: 'Dispur', district: 'Kamrup Metropolitan', state: 'ASSAM', country: 'INDIA', latitude: 26.1433, longitude: 91.7898 },
  { pincode: '781008', officeName: 'Dispur Basistha', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Guwahati', regionName: 'Assam', circleName: 'Assam', taluk: 'Dispur', district: 'Kamrup Metropolitan', state: 'ASSAM', country: 'INDIA', latitude: 26.1433, longitude: 91.7898 },
  { pincode: '781009', officeName: 'Dispur Sonapur', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Guwahati', regionName: 'Assam', circleName: 'Assam', taluk: 'Dispur', district: 'Kamrup Metropolitan', state: 'ASSAM', country: 'INDIA', latitude: 26.1433, longitude: 91.7898 },

  // Puducherry
  { pincode: '605001', officeName: 'Puducherry H.O', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Pondicherry', regionName: 'Tamilnadu', circleName: 'Tamilnadu', taluk: 'Puducherry', district: 'Puducherry', state: 'PUDUCHERRY', country: 'INDIA', latitude: 11.9416, longitude: 79.8083 },
  { pincode: '605002', officeName: 'Puducherry Muthialpet', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Pondicherry', regionName: 'Tamilnadu', circleName: 'Tamilnadu', taluk: 'Puducherry', district: 'Puducherry', state: 'PUDUCHERRY', country: 'INDIA', latitude: 11.9416, longitude: 79.8083 },
  { pincode: '605003', officeName: 'Puducherry Kuruchikuppam', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Pondicherry', regionName: 'Tamilnadu', circleName: 'Tamilnadu', taluk: 'Puducherry', district: 'Puducherry', state: 'PUDUCHERRY', country: 'INDIA', latitude: 11.9416, longitude: 79.8083 },
  { pincode: '605004', officeName: 'Puducherry Orleanpet', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Pondicherry', regionName: 'Tamilnadu', circleName: 'Tamilnadu', taluk: 'Puducherry', district: 'Puducherry', state: 'PUDUCHERRY', country: 'INDIA', latitude: 11.9416, longitude: 79.8083 },
  { pincode: '605005', officeName: 'Puducherry Nellithope', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Pondicherry', regionName: 'Tamilnadu', circleName: 'Tamilnadu', taluk: 'Puducherry', district: 'Puducherry', state: 'PUDUCHERRY', country: 'INDIA', latitude: 11.9416, longitude: 79.8083 },

  // Daman
  { pincode: '396210', officeName: 'Daman H.O', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Daman', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Daman', district: 'Daman', state: 'DAMAN AND DIU', country: 'INDIA', latitude: 20.3974, longitude: 72.8328 },
  { pincode: '396211', officeName: 'Daman Nani Daman', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Daman', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Daman', district: 'Daman', state: 'DAMAN AND DIU', country: 'INDIA', latitude: 20.3974, longitude: 72.8328 },
  { pincode: '396212', officeName: 'Daman Moti Daman', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Daman', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Daman', district: 'Daman', state: 'DAMAN AND DIU', country: 'INDIA', latitude: 20.3974, longitude: 72.8328 },
  { pincode: '396213', officeName: 'Daman Dabhel', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Daman', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Daman', district: 'Daman', state: 'DAMAN AND DIU', country: 'INDIA', latitude: 20.3974, longitude: 72.8328 },
  { pincode: '396214', officeName: 'Daman Bhimpore', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Daman', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Daman', district: 'Daman', state: 'DAMAN AND DIU', country: 'INDIA', latitude: 20.3974, longitude: 72.8328 },

  // Diu
  { pincode: '362520', officeName: 'Diu H.O', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Diu', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Diu', district: 'Diu', state: 'DAMAN AND DIU', country: 'INDIA', latitude: 20.7141, longitude: 70.9873 },
  { pincode: '362521', officeName: 'Diu Bucharwada', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Diu', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Diu', district: 'Diu', state: 'DAMAN AND DIU', country: 'INDIA', latitude: 20.7141, longitude: 70.9873 },
  { pincode: '362522', officeName: 'Diu Fudam', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Diu', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Diu', district: 'Diu', state: 'DAMAN AND DIU', country: 'INDIA', latitude: 20.7141, longitude: 70.9873 },
  { pincode: '362523', officeName: 'Diu Ghoghla', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Diu', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Diu', district: 'Diu', state: 'DAMAN AND DIU', country: 'INDIA', latitude: 20.7141, longitude: 70.9873 },
  { pincode: '362524', officeName: 'Diu Malala', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Diu', regionName: 'Gujarat', circleName: 'Gujarat', taluk: 'Diu', district: 'Diu', state: 'DAMAN AND DIU', country: 'INDIA', latitude: 20.7141, longitude: 70.9873 },

  // Lakshadweep
  { pincode: '682555', officeName: 'Kavaratti H.O', officeType: 'Head Office', deliveryStatus: 'Delivery', divisionName: 'Lakshadweep', regionName: 'Kerala', circleName: 'Kerala', taluk: 'Kavaratti', district: 'Lakshadweep', state: 'LAKSHADWEEP', country: 'INDIA', latitude: 10.5667, longitude: 72.6167 },
  { pincode: '682556', officeName: 'Agatti', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Lakshadweep', regionName: 'Kerala', circleName: 'Kerala', taluk: 'Agatti', district: 'Lakshadweep', state: 'LAKSHADWEEP', country: 'INDIA', latitude: 10.8500, longitude: 72.1833 },
  { pincode: '682557', officeName: 'Amini', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Lakshadweep', regionName: 'Kerala', circleName: 'Kerala', taluk: 'Amini', district: 'Lakshadweep', state: 'LAKSHADWEEP', country: 'INDIA', latitude: 11.1167, longitude: 72.7333 },
  { pincode: '682558', officeName: 'Androth', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Lakshadweep', regionName: 'Kerala', circleName: 'Kerala', taluk: 'Androth', district: 'Lakshadweep', state: 'LAKSHADWEEP', country: 'INDIA', latitude: 10.8167, longitude: 73.6833 },
  { pincode: '682559', officeName: 'Kalpeni', officeType: 'Sub Office', deliveryStatus: 'Delivery', divisionName: 'Lakshadweep', regionName: 'Kerala', circleName: 'Kerala', taluk: 'Kalpeni', district: 'Lakshadweep', state: 'LAKSHADWEEP', country: 'INDIA', latitude: 10.0667, longitude: 73.6333 }
];

async function seedDatabase() {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    console.log('Connected to MongoDB');

    // Clear existing data
    await Pincode.deleteMany({});
    console.log('Cleared existing data');

    // Insert comprehensive sample data
    await Pincode.insertMany(comprehensiveData);
    console.log(`Seeded ${comprehensiveData.length} PIN code records from major Indian cities`);

    console.log('Database seeded successfully!');
  } catch (error) {
    console.error('Error seeding database:', error);
  } finally {
    await mongoose.connection.close();
    console.log('Database connection closed');
  }
}

// Run the seed function
seedDatabase();